global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9091']
        labels:
          service: 'user-service'

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:9092']
        labels:
          service: 'task-service'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:9093']
        labels:
          service: 'notification-service'

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:9090']
        labels:
          service: 'gateway'
