global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: 'api-gateway'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']
        labels:
          service: 'user-service'

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:9093']
        labels:
          service: 'task-service'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8082']
        labels:
          service: 'notification-service'

  - job_name: 'org-service'
    static_configs:
      - targets: ['org-service:9094']
        labels:
          service: 'org-service'
